### ISSUE TITLE
false positive in presence of multiple patched ranges

### ISSUE THREAD

**Issue by robjtede** [deps-rs/deps.rs#132]
Example:
https://deps.rs/crate/actix-web-lab/0.2.2

- Requirement: `^1.8.4`
- Patched:
	- `>=1.8.4, <1.9.0`
	- `>=1.13.1`

Havent dug into it but I guess it's only checking the latest patched range.

**Comment by silamon** [comment]
This is technically correct and perhaps not a false positive. This issue should be closed, I guess. 

The advisory above has been updated in the meantime, so let's take a similar more recent example: 
https://deps.rs/repo/github/actix/actix-web?path=%2Factix-http

This repo has a requirement: `tokio = { version = "1.18.5", features = ["net", "rt", "macros"] }` shown as `
tokio ⚠️ | ^1.18.5 | 1.25.0 | maybe insecure`. All correct, since ^1.18.5 resolves into any version from >=1.18.5 to <2.0.0 whereof >=1.18.4, <1.19.0, >=1.20.3, <1.21.0, >=1.23.1 are secure versions. But other versions in between are known to be insecure. If another crate mentions `tokio = { version = "=1.19.0", features = ["full"] }`, actix-http would be build with 1.19.0 since according to the Cargo.toml of both crates, it is valid to use that version. Hence, "maybe insecure" is mentioned.

**Comment by robjtede** [comment]
Thanks, yeah. I've come across this again recently and come to the conclusion that it's accurate to say maybe insecure in this case. Will close.
