### ISSUE TITLE
Option for badge to show out-of-date minor versions

### ISSUE THREAD

**Issue by BartMassey** [deps-rs/deps.rs#142]
Right now, if a dependency is at `1.1.2` on crates.io, but at `1.1.1` in my project, it is shown by the badge as "up to date". I would like to be able to somehow configure the badge so that this is alerted somehow. That minor version is backward compatible according to semver, but it might also contain new functionality or bugfixes. In case it does, I would like to be prompted to rebuild my crate.

**Comment by robjtede** [comment]
We've designed the service according to best practices, and allowing a version range for a lib is part of that. As you've said, `1.1.2` is compatible with `1.1.1` (really: `^1.1.1`) so the badge is correct.

If you depend on `1.1` because of some feature that was introduced in `1.1.0` then that should be the version requirement in Cargo.toml even if there is a `1.2.0` that is released. This way it is up to application developers who use the library to run `cargo update` to receive bug fixes according to versions in their lockfiles.

**Comment by BartMassey** [comment]
Fair enough. Thanks.
