### ISSUE TITLE
web server upgrade

### ISSUE THREAD

**Issue by robjtede** [deps-rs/deps.rs#221]
Given the trimmed down scope of hyper v1, it's probably going to be just as much work, if not more, to upgrade to that vs any other server lib/framework.

Possibilities, alphabetical:

- Actix Web
- Axum: TODO
- Hyper v1
- Leptos (full-stack)
- Poem

Contributors, feel free to edit this post to add your ideas to the list.

**Comment by robjtede** [comment]
My bias is obviously towards Actix Web but it's intersting being involved with a different flavored project to keep knowledge of "the other side" fresh.

**Comment by Enet4** [comment]
I'm not sure why I locked this issue. Must've been a misclick, sorry. 😨 

It is interesting that this project has used Hyper for the web server, which AFAIUI is more of a library than a framework, and has required the developers involved to do a lot more work from the ground up in order to have a fully functional server. I agree that we are better off with picking a more substantial web framework this time. Aside from hyper, I see no impediment to the use of any of the frameworks listed, they all seem capable of fulfilling our needs. I happen to only have some experience in Actix Web, but the other ones should not be too complicated to pick up either.

In terms of popularity, Axum has more total crate downloads (44.8M), followed by Actix Web (19.7M).

Given the isomorphic nature of Leptos, someone experienced with it could clarify if it would require us to rewrite the frontend, or just make way for other frontend niceties in the future.

**Comment by robjtede** [comment]
> In terms of popularity, Axum has more total crate downloads

FWIW, those numbers are skewed quite sigificantly by its default inclusion in `tonic`. If just the router was split to a separate crate you'd see a marked decrease.

I'm gonna spend some time today doing both conversions and we can see with PRs which is nicer for us.

**Comment by robjtede** [comment]
using `actix-http`: https://github.com/deps-rs/deps.rs/pull/224

**Comment by robjtede** [comment]
- actix-http: https://github.com/deps-rs/deps.rs/pull/224
- Actix Web: https://github.com/deps-rs/deps.rs/pull/229
- axum (lite): https://github.com/deps-rs/deps.rs/pull/225
- axum: https://github.com/deps-rs/deps.rs/pull/228

**Comment by robjtede** [comment]
@contributors Would appreciate opinions on the above PRs.

Confirmed on Tokio's discord that axum (full) is the only variant here which doesn't properly support our current routing structure. We'd have to do manual path parsing for `/repo/...` routes.
