### ISSUE TITLE
Investigate issues with semver 0.11

### ISSUE THREAD

**Issue by paolobarbolini** [deps-rs/deps.rs#63]
It looks like `semver` 0.11 doesn't support parsing exact versions anymore, which lead to us downgrading it to 0.10 in #60

**Comment by Enet4** [comment]
The current version of semver can no longer parse version requirements if one of its pre-release identifiers starts with at least one digit and is followed by a letter or hyphen. Examples:  `1.2.0-rc.1x`, `0.1.0-next.123-`. This breaks due to some projects depending on `tower-make@=0.3.0-alpha.2a`. I couldn't find an issue at semver, so I might as well file it there.
