### ISSUE TITLE
CD: stressing staging shows caching issues

### ISSUE THREAD

**Issue by cecton** [deps-rs/deps.rs#80]
When going on https://staging.deps.rs/repo/github/rusoto/rusoto it is possible to get a "Failed to analyze repository" error.

On deps.rs it takes about 1 second to load from a cold cache but it always works. On staging.deps.rs when it fails it does so immediately.

Both were running on the same version.

cc @paolobarbolini

**Comment by paolobarbolini** [comment]
I was able to observe this issue multiple times in the same minute, but when it starts working refreshing immediately always seems to work, so my guess is that the issue happens when the crate info cache expires ([it only lasts 10 seconds](https://github.com/deps-rs/deps.rs/blob/fc899907715334763f98cae1947d7401afa4c55e/src/engine/mod.rs#L49-L53)).

Since the crates.io-index is cloned normally, reading a dependency's info just involves reading a file from disk. We do however do it in parallel between crates, so it probably opening many file descriptors?

**Comment by cecton** [comment]
This might be relevant: https://crates.io/crates/fdlimit

**Comment by kid** [comment]
Can't reproduce it anymore, I think it only happened before I rebase #79 to include the caching from #69 
It now loads in about a second every time

From within the container:

```
$ ulimit -aH
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        unlimited
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 16384
process              unlimited
nofiles              1048576
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
```

**Comment by paolobarbolini** [comment]
It was probably all of the registry crates loading from GitHub's API then, so this could now probably be considered as solved.

**Comment by cecton** [comment]
Ok! @kid will do the switch of DNS if there is no more problem
