### ISSUE TITLE
image dep shows as insecure, but the crate is not insecure

### ISSUE THREAD

**Issue by wez** [deps-rs/deps.rs#94]
Data seems inconsistent:

https://deps.rs/repo/github/wez/wezterm and search for `image`; it shows the following:

```
image | ^0.23 | 0.23.12 | insecure
```

clicking through to image:

https://deps.rs/crate/image/0.23.12

everything there is green.

**Comment by wez** [comment]
The same issue with https://deps.rs/crate/ordered-float/2.0.1

**Comment by Enet4** [comment]
This is caused by the current advisory database entry selection criteria. The database is queried for vulnerabilities in the given crate that may exist in _any_ version within the range.

In that case, `image` contains the vulnerability [RUSTSEC-2020-0073](https://rustsec.org/advisories/RUSTSEC-2020-0073.html) 
 which was patched in version `0.23.12`, but the dependent project admits the version range `^0.23`. Similar behavior is happening to dependents of `ordered-float`, `smallvec`, and potentially other crates.

Now, from my point of view, project maintainers should not be required to narrow the tail of their dependency constraints every time a vulnerability pops up in previous versions within the accepted version range. If all they have to do to ensure that their project is unaffected is to run `cargo update`, then I agree that this should not be called out as insecure by deps.rs. We can defer the handling of old lockfiles to #26.

**Comment by robjtede** [comment]
> Now, from my point of view, project maintainers should not be required to narrow the tail of their dependency constraints

I actually do this with actix packages and find deps.rs really useful in finding such ranges.

**Comment by Enet4** [comment]
Well yes, this is a bit opinionated, and we might need a better compromise. What deps.rs could do here is

- list all known vulnerabilities that the project might inherit from dependencies if unless they are not up to date;
- while still presenting the project either as _OK_ or _possibly insecure_, in a colder colour than red.

If this is agreed on, we can make further changes to #98 accordingly.

**Comment by robjtede** [comment]
Ueah both of those is ideal. I do feel that #98 is closer to that than current behavior.

**Comment by johan-bjareholt** [comment]
> @Enet4 
> Well yes, this is a bit opinionated, and we might need a better compromise. What deps.rs could do here is
>  - list all known vulnerabilities that the project might inherit from dependencies unless they are up to date;
>  - while still presenting the project either as OK or possibly insecure, in a colder colour than red.

Wouldn't the most correct thing be to check what version is specified in Cargo.lock? Since when you do "cargo build" it will use what's actually in the lock file rather than the newest patch version of the minor version specified in Cargo.toml.

**Comment by Enet4** [comment]
@johan-bjareholt I see it more as this problem becoming non-existent when reading the Cargo.lock file. :) But that is not implemented yet in deps.rs (#26), and not all projects are expected to commit these lock files anyway, meaning that we will always need some strategy for handling outdated versions without them.
