### ISSUE TITLE
Complains about CVE for old version

### ISSUE THREAD

**Issue by est31** [deps-rs/deps.rs#97]
Thanks to #96 I can now see what's going on in my [cargo-udeps crate's report](https://deps.rs/repo/github/est31/cargo-udeps). Apparently it complains about [CVE-2019-16760](https://rustsec.org/advisories/CVE-2019-16760.html) which affects cargo versions 0.26.0 and below, but versions above are fixed. My cargo-udeps tool requires cargo versions `^0.50.0`, so would never use `0.26.0` or below.

I guess the cause for this false positive is because cargo versioning is different from rust versioning. For rust version `1.n.0`, the corresponding cargo version is `0.{n+1}.0`. The CVE apparently expresses the bug in terms of the rust version, not the cargo version. Of course 0.27.0 or even 0.50.0 is below 1.27.0.

I'm not sure whether this is a bug with the rustsec database or with deps.rs. Pinging @tarcieri and @Shnatsel just in case.

**Comment by tarcieri** [comment]
The @RustSec project does not manage vulnerabilities for the Rust project itself.

You want the [Security Response WG](https://www.rust-lang.org/governance/wgs/wg-security-response).

**Comment by Shnatsel** [comment]
Looks like an issue with RustSec DB or tooling, actually. We do track this in the DB, but the versioning is really unhelpful for crate auditing purposes.

**Comment by est31** [comment]
I guess this is the file in the RustSec DB: https://github.com/RustSec/advisory-db/blob/master/rust/cargo/CVE-2019-16760.md

Maybe the cargo crate, as it's uploaded to crates.io, should get a separate entry in `crates/`, duplicating that report, with the right version numbers? Generally, as rustc is crates.io-ified, more crates might make their way onto crates.io in the future (beyond the library crates maintained by the official rust team, like idk socket2).

**Comment by tarcieri** [comment]
@est31 that seems like a reasonable workaround

**Comment by Shnatsel** [comment]
I believe libs.rs is erroneously applying advisory under rust/ directory in the advisory database, which versioned in Rust release terms, to cargo-the-crate and its version ranges.

I think this is an issue in libs.rs and not `rustsec` crate, because running `cargo audit` on another project that depends on Cargo does not surface any warnings about `cargo` crate.

However, now that I look the advisory database, it doesn't actually contain an advisory for Cargo versioned in crates.io terms; perhaps we should add it.

**Comment by Enet4** [comment]
I have been working on #94, and I can attest that deps.rs is reporting a few false positives. This is due to the way the advisory database is being queried for vulnerabilities at the moment. I will send in a PR to correct this soon.

Hopefully this should be the only problem. The way I see it, this issue and #94 reflect the same concern.

**Comment by lu-zero** [comment]
cargo-audit seems to work fine, maybe the same logic can be used in deps.rs ?

**Comment by tarcieri** [comment]
The logic in the `rustsec` crate was fixed in v0.25.

FYI, we're about to put out a v0.26.0. You might want to hold off upgrading until that if you haven't already.

**Comment by paolobarbolini** [comment]
It still seems broken in https://github.com/deps-rs/deps.rs/pull/152

**Comment by tarcieri** [comment]
@paolobarbolini I'll see if I can figure out what's wrong when I have some spare time

**Comment by paolobarbolini** [comment]
@tarcieri after looking further into it I found out the cause is https://github.com/deps-rs/deps.rs/blob/aa2e01f96bc5f964be8b053a2280dbd78304dd68/src/engine/machines/analyzer.rs#L43 using `Query::new()` instead of `Query::crate_scope()`. Doing so would mean completely ignoring cargo advisories though, which doesn't seem like a proper fix :confused:

**Comment by paolobarbolini** [comment]
Ok. I've opened #153 to correct the issue

**Comment by est31** [comment]
Yay it's green! Thank you, folks!
